"""PDF extraction and page-aware chunking.

The PDFs here are generated by PyMuPDF rather than committed as fixtures, so
the tests state what the input actually is instead of hiding it in a binary.
"""
from __future__ import annotations

import logging
import re
from typing import Sequence

import pymupdf
import pytest

from app.ingest.chunker import assemble_pages, chunk_pages
from app.ingest.pdf import pdf_document

WORD = re.compile(r"\S+")


def count_words(texts: Sequence[str]) -> list[int]:
    return [len(WORD.findall(t)) for t in texts]


def word_offsets(text: str) -> list[tuple[int, int]]:
    return [m.span() for m in WORD.finditer(text)]


def make_pdf(pages: list[str], title: str | None = None) -> bytes:
    doc = pymupdf.open()
    for body in pages:
        page = doc.new_page()
        page.insert_text((72, 96), body, fontsize=11)
    if title:
        doc.set_metadata({"title": title})
    data = doc.tobytes()
    doc.close()
    return data


def test_pages_are_extracted_in_order_and_flattened_for_the_viewer():
    data = make_pdf(["Access and environments", "Running services locally"])
    doc = pdf_document(data, name="handbook.pdf")

    assert doc.source_type == "pdf"
    assert doc.pages is not None and len(doc.pages) == 2
    assert "Access and environments" in doc.pages[0]
    assert "Running services locally" in doc.pages[1]
    # The flattened text is what the source viewer renders.
    assert doc.text == assemble_pages(list(doc.pages))[0]
    assert doc.meta["pages"] == 2


def test_title_comes_from_pdf_metadata_then_from_the_filename():
    with_title = pdf_document(make_pdf(["body"], title="Onboarding Handbook"), name="h.pdf")
    assert with_title.title == "Onboarding Handbook"

    without = pdf_document(make_pdf(["body"]), name="engineering_handbook.pdf")
    assert without.title == "engineering handbook"


def test_a_scanned_pdf_warns_instead_of_indexing_nothing(caplog):
    """An empty text layer imports without error and answers nothing."""
    data = make_pdf(["", "", ""])
    with caplog.at_level(logging.WARNING):
        doc = pdf_document(data, name="scan.pdf")

    assert doc.meta["pages_with_text"] == 0
    assert "text layer" in caplog.text
    assert "scan.pdf" in caplog.text


def test_chunks_carry_a_page_number_and_lines_into_the_flattened_text():
    pages = [
        "Alpha line one\nAlpha line two",
        "Beta line one\nBeta line two",
        "Gamma line one\nGamma line two",
    ]
    text, _ = assemble_pages(pages)
    lines = text.split("\n")

    chunks = chunk_pages(
        pages,
        max_tokens=50,
        overlap_tokens=0,
        count_tokens=count_words,
        token_offsets=word_offsets,
    )

    assert [c.page for c in chunks] == [1, 2, 3]
    assert [c.ordinal for c in chunks] == [0, 1, 2]
    for c in chunks:
        # The shifted range must still name the right lines in the flat text.
        assert c.content == "\n".join(lines[c.line_start - 1 : c.line_end])


def test_a_chunk_never_spans_two_pages():
    """Otherwise the page number on a citation would be a half-truth."""
    pages = ["one two three", "four five six", "seven eight nine"]
    chunks = chunk_pages(
        pages,
        max_tokens=100,  # generous enough to swallow all three pages at once
        overlap_tokens=0,
        count_tokens=count_words,
        token_offsets=word_offsets,
    )
    assert len(chunks) == 3
    for chunk, page in zip(chunks, pages):
        assert chunk.content == page


@pytest.mark.parametrize("pages", [[], [""]])
def test_empty_pdfs_produce_no_chunks(pages):
    assert (
        chunk_pages(
            pages,
            max_tokens=50,
            overlap_tokens=0,
            count_tokens=count_words,
            token_offsets=word_offsets,
        )
        == []
    )
